#define SPEED_MIN_INT 0
#define SPEED_MAX_INT 100
#define SPEED_MIN_DOUBLE 0.0
#define SPEED_MAX_DOUBLE 5.0
#define WIDTH_MIN_INT 1
#define WIDTH_MAX_INT 100
#define WIDTH_MIN_DOUBLE 0.8
#define WIDTH_MAX_DOUBLE 3.0